### ISSUE TITLE
Edit Rights

### ISSUE THREAD

**Issue by eapache** [graphql/graphql-scalars#5]
Something that occurred to me, to discuss: who should we accept edits from (or e.g. new versions of an existing scalar), besides the original author? Other members of a shared org seem obvious, but there's no obvious path for sharing ownership over a single author's scalar.

Not sure if this actually matters, or if we should be encouraging more of a fork-and-evolve model?

**Comment by andimarek** [comment]
Good point, but I think we can keep it simple. 

My expectation is that somebody authors a spec and then maybe edit some details over time (non major changes). As a general rule: nobody else should be allowed to modify the spec except the original author (but we can use common sense here: a typo can be fixed by everybody for example).

I think a new version of the same scalar by the same author happens rarely: A custom Scalar is not Software which evolves over time with new features.

Everything else is just a new Scalar by the same or another author. (fork and evolve model): you don't like my DateTime? Feel free to change it slightly and publish it under your name.

**Comment by dondonz** [comment]
Closing this issue as we have decided that specification semantics are immutable, but we will offer minor (non-semantic) edits such as typo fixes.
