### ISSUE TITLE
Blessing scalars for GraphQL-JS

### ISSUE THREAD

**Issue by eapache** [graphql/graphql-scalars#6]
To discuss: how do we want to bless certain custom scalars for inclusion in graphql-js? Is it just an ad-hoc vote of the working group? Or should we *not* bless any such scalars, and leave the community to figure it out? There's definitely a case to be made for standard reference implementations of some key ones like DateTime...

**Comment by andimarek** [comment]
If we add default Scalars to graphql-js they will become effectively standard Scalars, even if the Scalar is not part of the GraphQL spec. 

In GraphQL Java we decided to publish some Scalars as an extra artifact and not in GraphQL Java itself, because they are not part of the GraphQL Spec. Also because they are not part of the GraphQL spec we expect them to change more often and therefore we didn't want to couple the release and the maintenance together.
