### ISSUE TITLE
Contribution agreement and license

### ISSUE THREAD

**Issue by andimarek** [graphql/graphql-scalars#7]
This being part of the GraphQL foundation I expect that everybody needs to sign the CLA of the foundation before the code can be merged. @leebyron that correct?

Also: which license should be used for the specs?

The GraphQL spec itself states:
```This specification was licensed under OWFa 1.0 in 2017. Copyright and trademark was transferred to the GraphQL Foundation in 2019.```

I would expect we do the same for custom Scalars specs.

**Comment by brianwarner** [comment]
That's correct, everyone needs to agree to the specification membership agreement by signing either as an [individual](https://individual-spec-membership.graphql.org) or if they're doing this for their work, have their [company](https://corporate-spec-membership.graphql.org) sign for them.

As with the spec working group, there will need to be meeting agendas and minutes, and participants must add themselves to the agenda via PR if they join a meeting or open a pull request so that we have a record of their participation.

The license for the specs would be the same as for the GraphQL spec: OWF for the spec, OWFa for the patent license, and MIT for the code.

**Comment by andimarek** [comment]
@brianwarner thanks fo the explanation. 

How do we check that people actually signed the specification membership agreement? 

One of our goals is to make it as easy as possible to contribute custom Scalars specs: we are planning to merge PRs for example without any discussion about the content as long as same formal rules are followed.

**Comment by dondonz** [comment]
Closing this issue as EasyCLA has been added to the repo.
